### ISSUE TITLE
USB Power Not Detected

### ISSUE THREAD

**Issue by jhughesoti** [wuspy/portal_calendar#21]
I had a previous version of this project running on an esp32 board that was not the same one used in the description without issue.  I saw that there was a lot of updates recently and wanted to try it so after compiling and uploading without any changes, I get a Not on USB power message, which it is.  I don't see any additional wiring that's going on or anything other than setting some pin behaviors for PIN 19.  Is this a specific behavior to this board?  

I do actually have the same board in the hardware specs and tested with that one and it does detect USB power.  Same code, two different esp32 dev boards, different usb power behaviors so not sure if this is a specific feature to this board or the choice of pin 19 is specific to the board.

**Comment by wuspy** [comment]
Yeah, unfortunately #17 added some code specific to this board to determine if it's running on USB power. Vusb is connected to pin 19 through an LED and a 1k resistor. You can check to see if the board you're using has some method for determining if it's running on USB power and then change the value of PD_PIN in config.h to match it, or write some custom code if it's not as simple as just checking a pin. Most boards don't have such a feature though.

If you're dead set on using this board you can always add a switch on some unused pin and use that to trigger the web server. Or even bodge a resistor divider or a similar LED/resistor pair between Vusb and a random pin. I don't actually know if the ESP32 is 5v tolerant so just running a wire might not be safe. Or of course you could just keep running the last commit before that PR was merged, no other new features have been added yet.

Closing for now since this is related to an unsupported board.
